INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('Wormhole ',5029,'oooooooo-oooo-oooo-oooo-oooooooooooo','Year 3000: Earth is dying. A Wormhole appears. Desperate and with their final shard of optimism, the last of survivors go on a failed mission to find a way off their home planet. Now trapped, the security detail took their gear through the mysterious portal and entered a maze from another world. Only one man returned, his limb a sacrificial token to the abyss of a maze. You are the brave son/daughter of one of those lost to the maze. It is now up to you to fight zombies and find the maze exit, to a better place窶ｦ or not窶ｦ','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000099B','Andrew Andy Chng Chee Weng','a@nus.edu.sg',60000098,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000099B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000099B','5029');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000100B',' Chua Hao Eng','a@nus.edu.sg',60000099,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000100B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000100B','5029');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000101B',' Goh Hui May','a@nus.edu.sg',60000100,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000101B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000101B','5029');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000102B',' Yeap Si Rui','a@nus.edu.sg',60000101,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000102B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000102B','5029');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000103B',' Zhang Yiwen ','a@nus.edu.sg',60000102,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000103B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000103B','5029');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('Dash! ',5030,'oooooooo-oooo-oooo-oooo-oooooooooooo','A girl is transported to a world where she must jump, dodge and hack her way to the goal according to the rhythm of the level. The levels are dynamically generated by running a music file through a series of Fourier transform and wave analysis algorithms and then pegging an obstacle to certain cues in the music. Players can choose to import their own music files into the game and generate a level from there to play with.','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000104B','TAN Li Boon','a@nus.edu.sg',60000103,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000104B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000104B','5030');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000105B',' FAZLI Sapuan','a@nus.edu.sg',60000104,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000105B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000105B','5030');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000106B',' TAN Tack Poh','a@nus.edu.sg',60000105,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000106B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000106B','5030');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000107B',' TANG Huan Song','a@nus.edu.sg',60000106,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000107B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000107B','5030');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000108B',' Jenna TAY Xiu Li ','a@nus.edu.sg',60000107,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000108B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000108B','5030');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('Illuminate ',5031,'oooooooo-oooo-oooo-oooo-oooooooooooo','These days horror game is becoming rare although there are notable ones. The project aims to make a horror game revolving around light. Player is required to exorcise demons using light which can be replenished at the price of losing light source like lamps around the building - thus vision. The project is compatible with Oculus Rift for those who would like more immersive experience.','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000109B','Terence Rei Jie Then','a@nus.edu.sg',60000108,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000109B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000109B','5031');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000110B',' Hans Adrian','a@nus.edu.sg',60000109,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000110B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000110B','5031');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000111B',' Christopher Andy Weidya','a@nus.edu.sg',60000110,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000111B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000111B','5031');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000112B',' Ko Wan Ling','a@nus.edu.sg',60000111,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000112B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000112B','5031');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000113B',' Tan Zheng Jie Matthew ','a@nus.edu.sg',60000112,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000113B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000113B','5031');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('Broken ',5032,'oooooooo-oooo-oooo-oooo-oooooooooooo','Broken is a third person action adventure game for PCs and consoles. The story revolves around a multi-millionaire who is deceitfully framed and lands up in a high-security prison. The player aids the protagonist in navigating a world filled with known and unknown dangers of a jail. Guide the protagonist through different parts of the prison as he uncovers the motives of the evil Warden. Engage yourself in an intense gameplay involving breath-taking fight sequences as he parkours his way past imminent death.','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000114B','Akaash Gupta','a@nus.edu.sg',60000113,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000114B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000114B','5032');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000115B',' Aravindhan Duraisamy','a@nus.edu.sg',60000114,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000115B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000115B','5032');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000116B',' Shailen Aggarwal','a@nus.edu.sg',60000115,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000116B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000116B','5032');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000117B',' Ho Tack Kian ','a@nus.edu.sg',60000116,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000117B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000117B','5032');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('Animal Revolt! ',5033,'oooooooo-oooo-oooo-oooo-oooooooooooo','Accused of false crimes. Exiled from the place you call home. These were the circumstances when you left everything behind. Having spent the past year on the run, you now hear of how dystopian your home has become. The time to run has ended. Your home needs you. Animal Farm needs you. In Animal Revolt!, you play as Snowball: revolutionary from the book Animal Farm. Restore peace and equality to the farm by using your bazooka. Load animals. Load tractors. Load walls. Anything can be ammunition. Use the environment wisely, because your enemies are smart enough to do the same.','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000118B','Yong Jia Jie','a@nus.edu.sg',60000117,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000118B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000118B','5033');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000119B',' Kuek Kiang Kuang','a@nus.edu.sg',60000118,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000119B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000119B','5033');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000120B',' Chan Ao Wei Oswell','a@nus.edu.sg',60000119,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000120B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000120B','5033');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000121B',' Hsu Cheng Hsien ','a@nus.edu.sg',60000120,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000121B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000121B','5033');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('Candy Run ',5034,'oooooooo-oooo-oooo-oooo-oooooooooooo','Two kids went out to look for food since they were left alone for too long by their parents. They came into a house made of candy and certainly they start enjoying the house. However the house is actually a trap set by an evil witch. She started chasing the two children with her evil tools. Can the children survive this fatal moment? Their destiny is in your hand! Start running and help them escape from the witch!','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000122B','Li Anbang','a@nus.edu.sg',60000121,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000122B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000122B','5034');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000123B',' Cao Shengze','a@nus.edu.sg',60000122,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000123B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000123B','5034');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000124B',' Wen Yiran','a@nus.edu.sg',60000123,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000124B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000124B','5034');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000125B',' Weng Yuan','a@nus.edu.sg',60000124,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000125B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000125B','5034');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000126B',' Zhang Xiang ','a@nus.edu.sg',60000125,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000126B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000126B','5034');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('Power Racer - "Go Go Power" Racers! ',5035,'oooooooo-oooo-oooo-oooo-oooooooooooo','Power Racers is a light hearted multiplayer racing game that references elements from a third-person shooter game and a competitive arcade racing game. Goal of the game is to compete with your opponents to see who completes the race first. Players can choose to race with AIs or with other players through the online platform. The player can choose to play the game with MYO, Logitech Station Steering Wheel or with the very own keyboard on their desktops. 窶弃ower Racers窶� adopts a less serious approach with intended in-game art to appeal even to the age group of 7-12 years old.','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000127B','Kevin Wong Jun Jie','a@nus.edu.sg',60000126,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000127B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000127B','5035');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000128B',' Lau Tze Hao Darren','a@nus.edu.sg',60000127,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000128B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000128B','5035');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000129B',' Weilson Tan','a@nus.edu.sg',60000128,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000129B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000129B','5035');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000130B',' Phan Shi Yu ','a@nus.edu.sg',60000129,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000130B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000130B','5035');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('Myoro ',5036,'oooooooo-oooo-oooo-oooo-oooooooooooo','In this technology-driven age, where world has been attacked by worms and spywares. In order to save the world, our protagonist have to defeat the powerful V.I.R.U.S.(Vicious Insane Random Uncontrollable Subroutine). With the use of Myo Armband and VR HeadSet, the player will enter the world to annihilate the final boss and its minions with the use of spells and equipments through Myo Armband gestures. The goal of the game is to collect all the keys required to reach V.I.R.U.S, the final boss, and defeat it.','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000131B','Sophia Yuen Shu Hui','a@nus.edu.sg',60000130,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000131B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000131B','5036');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000132B',' Stella Widyasari','a@nus.edu.sg',60000131,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000132B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000132B','5036');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000133B',' Camille Waligora','a@nus.edu.sg',60000132,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000133B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000133B','5036');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000134B',' Liu Jiale','a@nus.edu.sg',60000133,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000134B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000134B','5036');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000135B',' Maciej Ziarkowski ','a@nus.edu.sg',60000134,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000135B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000135B','5036');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('Jack the Jetrider ',5037,'oooooooo-oooo-oooo-oooo-oooooooooooo','The evil Dr. Beanstalk kidnaps Jack after learning that he is a young prodigy and imprisons him. Jack is forced to make a device for Dr. Beanstalk so that he can take over the world! When Jack has finished the Jump Enhancing Taxi (aka J.E.T), instead of handing it over to the evil doctor, he decides to use it himself! Jack the Jetrider has to keep running to escape the grasp of Dr. Beanstalk! The way ahead is full of uncertainty. Will he break out and make his own legend?','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000136B','Chue Sai Hou','a@nus.edu.sg',60000135,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000136B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000136B','5037');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000137B',' Bui Trong Nhan','a@nus.edu.sg',60000136,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000137B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000137B','5037');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000138B',' Sivan Nanthiran','a@nus.edu.sg',60000137,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000138B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000138B','5037');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000139B',' Liu Yuanrui','a@nus.edu.sg',60000138,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000139B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000139B','5037');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000140B',' He Buwei ','a@nus.edu.sg',60000139,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000140B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000140B','5037');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('FREEZE ',5038,'oooooooo-oooo-oooo-oooo-oooooooooooo','Freeze is a first-person action-adventure game that is focused around being a virtual reality game (that will make use of the Oculus Rift). It is a level-based on-rails runner where the player automatically moves through a series of levels (with some lateral control) and has to dodge bullets being fired at him and also avoid other obstacles in the level. The core mechanic of the game is the player窶冱 ability to 窶彷reeze窶� or slow down time, allowing him to assess the situation around him and figure out the best way to navigate through the level.','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000141B','Kang-An','a@nus.edu.sg',60000140,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000141B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000141B','5038');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000142B',' Ooh Jing','a@nus.edu.sg',60000141,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000142B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000142B','5038');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000143B',' Justin Doan','a@nus.edu.sg',60000142,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000143B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000143B','5038');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000144B',' Abel Tan ','a@nus.edu.sg',60000143,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000144B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000144B','5038');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('Cat-astrophe! ',5039,'oooooooo-oooo-oooo-oooo-oooooooooooo','Cat-astrophe! is an immersive 3D action game, where you play as Nyan, a cute kitten, as he explores his environment and hunts for food. Play in Nyan窶冱 paws by mimicking his natural movements using the Leap Motion sensor, and see from his eyes with the Oculus Rift! Grow larger the more you eat, and soon you will be able to take on larger enemies and obstacles. An A-meow-zing adventure awaits!','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000145B','Qwek Siew Weng Melvyn','a@nus.edu.sg',60000144,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000145B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000145B','5039');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000146B',' Chng Xinni','a@nus.edu.sg',60000145,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000146B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000146B','5039');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000147B',' Lim Wancai Daryl','a@nus.edu.sg',60000146,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000147B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000147B','5039');
INSERT INTO `user` (`user_id`,`name`,`email`,`contact`,`user_type`,`food_preference`) VALUES
('A5000148B',' Nguyen Trung Hieu ','a@nus.edu.sg',60000147,2,1);
INSERT INTO `enrolled` (`user_id`,`module_id`) VALUES ('A5000148B','oooooooo-oooo-oooo-oooo-oooooooooooo');
INSERT INTO `participate` (`user_id`,`project_id`) VALUES ('A5000148B','5039');