INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('CodeCraft ',5040,'tttttttt-tttt-tttt-tttt-tttttttttttt','CodeCraft is a web based visual programming Integrated Development Environment (IDE), inspired by SNAP!. It lets users program their own interactive and animated stories and games, by using drag-and-drop to combine blocks that each execute specific commands. It can be used as a teaching tool to introduce basic programming concepts to young children.','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('Interactive Human Anatomy ',5041,'tttttttt-tttt-tttt-tttt-tttttttttttt','The Interactive Human Anatomy Project aims to create an independent learning platform for the Department of Anatomy in the Yong Loo Lin School of Medicine. It will focus on the 3D interaction of human systems with text annotations as well as the display of videos and presentations/notes and support of MCQ self-assessment quizzes for students. In order to better organize the massive amount of content, course material will be separated into different lessons.','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('Animated History of the World ',5042,'tttttttt-tttt-tttt-tttt-tttttttttttt','AnimHist is a web application that provides an easy way to create and view interactive historical data, so as to enrich the experience of learning about historical events. Historical data is often dense and difficult to comprehend and visualize due to the vast amount of data involved. AnimHist aims to change that by allowing users to easily visualise the data through interactive and animated graphics instead of reading the raw numbers.','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('Integrated Surgery Training Curriculum ',5043,'tttttttt-tttt-tttt-tttt-tttttttttttt','Integrated Surgery Training Curriculum provides surgeons with an integrated platform to manage their trainings, researches and administrative duties like their training activities, leave applications, call rosters, personal notes and assessments. This project is supervised by Associate Professor Leow Wee Kheng from School of Computing (SoC) of National University of Singapore (NUS) and Consultant Surgeon Dr Ooi Oon Cheong from the National University Heart Centre, Singapore, with the assistance of Jai Sule (Star Trainee) from the National University Hospital (NUH).','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('PPCDL ',5044,'tttttttt-tttt-tttt-tttt-tttttttttttt','The Powered Pleasure Craft Driving License (PPCDL) is required for the driving of powered pleasure crafts within Singaporeﾃｭs port limits. Obtaining a pass in both the theory and practical tests is necessary to get this license. With a license, one is allowed to operate powered pleasure crafts of length not more than 24 metres (excluding the propeller length).','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('Procedural Level/Content Generation Tool for Multiplayer Shooter Games ',5045,'tttttttt-tttt-tttt-tttt-tttttttttttt','The Powered Procedural Content Generation (PCG) is the use of algorithmic means to create content dynamically during run-time. In general, PCG brings about two major benefits. The first is the smaller size of the overall program, as we do away with complex models and images. The second is constantly changing and thus interesting content, which adds to player experience.','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('Ship Snapshot ',5046,'tttttttt-tttt-tttt-tttt-tttttttttttt','Ship Snapshot is an augmented reality marine navigation aid for mobile devices targeted at ship crew. Using sensor information available on a mobile device and additional information from external sources, the application overlays a ship information layer over live camera images.','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('Gently: Game Streaming System ',5047,'tttttttt-tttt-tttt-tttt-tttttttttttt','Gently is a live streaming video platform and community primarily for gamers. With a website as a front, Gently enables any gamer to broadcast live content on their computer to the site and allows any other person viewing the site to see the broadcasted content in real-time.','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');
INSERT INTO `project` (`title`,`project_id`,`module_id`,`abstract`,`poster`,`video`) VALUES 
('Forensics Suite ',5048,'tttttttt-tttt-tttt-tttt-tttttttttttt','The project objective is to develop a stand-alone desktop software which reads mobile device disk images, extract and recover content inside the image and output forensic analysis results in graphical format. The software will allow future developers to develop and implement new features through a plugin framework.','http://media.tumblr.com/3f81fad6ef163759fff8077580d94752/tumblr_inline_nj4nxkE0C21qersu1.png','https://www.youtube.com/watch?v=MYZfjfkwRII');