mysql test -e "source DDL.sql";
mysql test < user1.sql;
mysql test < user2.sql;
mysql test < user3.sql;
mysql test < user4.sql;
mysql test < user5.sql;
mysql test < user6.sql;
mysql test < prof.sql;
mysql test < module.sql;
mysql test < supervise.sql;
mysql test < BB3218.sql;
mysql test < SS3101.sql;
mysql test < ZZ3217.sql;
mysql test < 2person.sql;
mysql test < 3person.sql;
mysql test < 4person.sql;
mysql test < 5person.sql;
mysql test < iterate.sql;